import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders} from '@angular/common/http';
import { User } from '../Model/user';
import { CloneParameter } from '../Model/CloneParameter';
import { FolderParameter } from '../Model/FolderParameter';

@Injectable({
  providedIn: 'root'
})
export class TowerAPIService {

  constructor(private http: HttpClient) { }

  url = "https://172.10.6.157/api/v2/job_templates/";

  startJob(job_id:number,customer_name:String){  
   
    const httpOptions = {
      headers: new HttpHeaders({
        'Content-Type': 'application/json; charset=utf-8',
        'Authorization': 'Bearer 1E7LBSJ5rFrANQ3cWS1iQm9GA2N3r1'
      }),
      data: {"limit" : "ansible"}
    };

    var customer_id = "1231INT";
 
    var body_post = {
      "extra_vars":{
        "call_from_tower": true,
        "env_name": "dev",
        "vcenter_hostname": "photon-machine.localdomain",
        "vcenter_username": "administrator@vsphere.local",
        "vcenter_password": "Root718293?",
        "customer_id": customer_id,
        "customer_name": customer_name,
        "host_name": "172.10.3.29",
        "build_size": "medium",
        "datastore_name": "datastore2",
        "datastore_device_name": "mpx.vmhba0:C0:T0:L0",
        "datastore_type": "vmfs",
        "vmfs_version": 6,
        "folders_parameters": [
         {
          "datacenter_name": "Suwanee",
          "sub_folder_name": customer_id+" - "+customer_name,
          "parent_folder_name": "HCS Customers",
          "folder_state": "present",
          "cluster_name": "DEV-CLUSTER"
         },
         {
          "datacenter_name": "Denver",
          "sub_folder_name": customer_id+" - "+customer_name,
          "parent_folder_name": "HCS Customers",
          "folder_state": "present",
          "cluster_name": "TEMP-CLU01"
         }
        ],
        "clones_parameters": [
         {
          "datacenter_name": "Suwanee",
          "vm_state": "poweredoff",
          "vm_name": "INTCCM1S01SWN",
          "vm_template_name": "CUCM 11.5 SU6 7500usr Skip Template",
          "full_folder_path": "/HCS Customers/"+customer_id+" - "+customer_name,
          "datastore": "datastore8",
          "host": "172.10.6.153",
          "vm_final_state": "poweredoff",
          "vm_mac": "00:50:56:97:e4:b9",
          "vm_network_name": "VM Network",
          "answer_file_config": {
           "product_type": "cucm",
           "node_type": "secondary",
           "primary_host_name": "INTCCM1P01DEN",
           "primary_host_ip": "172.10.3.80",
           "host_name": "INTCCM1S01SWN",
           "host_ip": "172.10.3.81",
           "host_mask": "255.255.240.0",
           "host_gateway": "172.10.2.2",
           "primary_dns": "172.10.2.2",
           "secondary_dns": "",
           "domain_name": "local",
           "host_timezone": "America/Argentina/Buenos_Aires",
           "host_continent": "America",
           "host_city": "Argentina",
           "host_admin": "intrado_admin",
           "host_admin_password": "Int_ado1*",
           "host_security_password": "Int_ado1*",
           "host_app_user_password": "Int_ado1*",
           "certificate_organization": "Intrado-AR",
           "certificate_unit": "UCBOP-AR",
           "certificate_location": "Santa Fe",
           "certificate_state": "Santa Fe",
           "certificate_country": "AR",
           "locale_id": "",
           "ccm_version": "",
           "ccm_first_node": "no",
           "call_home_disable": "Disabled",
           "ip_security_first_node": "no",
           "app_user_username": "intrado_appuser"
          }
         },
         {
          "datacenter_name": "Suwanee",
          "vm_state": "poweredoff",
          "vm_name": "INTIMP1S01SWN",
          "vm_template_name": "IM&P 11.5 SU6 5000usr Skip Template",
          "full_folder_path": "/HCS Customers/"+customer_id+" - "+customer_name,
          "datastore": "datastore8",
          "host": "172.10.6.153",
          "vm_final_state": "poweredoff",
          "vm_mac": "00:50:56:97:e4:a1",
          "vm_network_name": "VM Network",
          "answer_file_config": {
           "product_type": "im&p",
           "node_type": "secondary",
           "imp_domain_name": "somedomain",
           "primary_host_name": "INTCCM1P01DEN",
           "primary_host_ip": "172.10.3.80",
           "host_name": "INTIMP1S01SWN",
           "host_ip": "172.10.3.82",
           "host_mask": "255.255.240.0",
           "host_gateway": "172.10.2.2",
           "primary_dns": "172.10.2.2",
           "secondary_dns": "",
           "domain_name": "local",
           "host_timezone": "America/Argentina/Buenos_Aires",
           "host_continent": "America",
           "host_city": "Argentina",
           "host_admin": "intrado_admin",
           "host_admin_password": "Int_ado1*",
           "host_security_password": "Int_ado1*",
           "host_app_user_password": "Int_ado1*",
           "certificate_organization": "Intrado-AR",
           "certificate_unit": "UCBOP-AR",
           "certificate_location": "Santa Fe",
           "certificate_state": "Santa Fe",
           "certificate_country": "AR",
           "locale_id": "",
           "ccm_version": "",
           "ccm_first_node": "no",
           "ip_security_first_node": "no",
           "app_user_username": "intrado_appuser"
          }
         },
         {
          "datacenter_name": "Suwanee",
          "vm_state": "poweredoff",
          "vm_name": "INTCUC1P01SWN",
          "vm_template_name": "IM&P 11.5 SU6 5000usr Skip Template",
          "full_folder_path": "/HCS Customers/"+customer_id+"- "+customer_name,
          "datastore": "datastore8",
          "host": "172.10.6.153",
          "vm_final_state": "poweredoff",
          "vm_mac": "00:50:56:97:e4:a2",
          "vm_network_name": "VM Network",
          "answer_file_config": {
           "product_type": "cucx",
           "node_type": "secondary",
           "host_name": "INTCUC1P01SWN",
           "host_ip": "172.10.3.83",
           "host_mask": "255.255.240.0",
           "host_gateway": "172.10.2.2",
           "primary_dns": "172.10.2.2",
           "secondary_dns": "",
           "domain_name": "local",
           "host_timezone": "America/Argentina/Buenos_Aires",
           "host_continent": "America",
           "host_city": "Argentina",
           "host_admin": "intrado_admin",
           "host_admin_password": "Int_ado1*",
           "host_security_password": "Int_ado1*",
           "host_app_user_password": "Int_ado1*",
           "certificate_organization": "Intrado-AR",
           "certificate_unit": "UCBOP-AR",
           "certificate_location": "Santa Fe",
           "certificate_state": "Santa Fe",
           "certificate_country": "AR",
           "locale_id": "",
           "ccm_version": "",
           "ccm_first_node": "yes",
           "call_home_disable": "Disabled",
           "ip_security_first_node": "yes",
           "auto_register_primary": "0",
           "app_user_username": "intrado_appuser",
           "ntp_server_1": "173.224.149.136",
           "ntp_server_2": "173.224.157.252",
           "ntp_server_3": "199.38.38.3"
          }
         },
         {
          "datacenter_name": "Suwanee",
          "vm_state": "poweredoff",
          "vm_name": "INTEWC1P01SWN",
          "vm_template_name": "Expressway C&E",
          "full_folder_path": "/HCS Customers/"+customer_id+" - "+customer_name,
          "datastore": "datastore8",
          "host": "172.10.6.153",
          "vm_final_state": "poweredoff",
          "vm_mac": "00:50:56:97:e4:a6",
          "vm_network_name": "VM Network",
          "answer_file_config": {
           "product_type": "cucm",
           "node_type": "secondary",
           "host_name": "INTEWC1P01SWN",
           "host_ip": "172.10.3.87",
           "host_mask": "255.255.240.0",
           "host_gateway": "172.10.2.2",
           "primary_dns": "172.10.2.2",
           "secondary_dns": "",
           "domain_name": "local",
           "host_timezone": "America/Argentina/Buenos_Aires",
           "host_continent": "America",
           "host_city": "Argentina",
           "host_admin": "intrado_admin",
           "host_admin_password": "Int_ado1*",
           "host_security_password": "Int_ado1*",
           "host_app_user_password": "Int_ado1*",
           "certificate_organization": "Intrado-AR",
           "certificate_unit": "UCBOP-AR",
           "certificate_location": "Santa Fe",
           "certificate_state": "Santa Fe",
           "certificate_country": "AR",
           "locale_id": "",
           "ccm_version": "",
           "ccm_first_node": "yes",
           "call_home_disable": "Disabled",
           "ip_security_first_node": "yes",
           "auto_register_primary": "0",
           "app_user_username": "intrado_appuser",
           "ntp_server_1": "173.224.149.136",
           "ntp_server_2": "173.224.157.252",
           "ntp_server_3": "199.38.38.3"
          }
         },
         {
          "datacenter_name": "Denver",
          "vm_state": "poweredoff",
          "vm_name": "INTCCM1P01DEN",
          "vm_template_name": "CUCM 11.5 SU6 7500usr Template",
          "full_folder_path": "/HCS Customers/"+customer_id+" - "+customer_name,
          "datastore": "datastore3",
          "host": "172.10.3.29",
          "vm_final_state": "poweredoff",
          "vm_mac": "00:50:56:97:e4:b8",
          "vm_network_name": "VM Network",
          "answer_file_config": {
           "product_type": "cucm",
           "node_type": "secondary",
           "host_name": "INTCCM1P01DEN",
           "host_ip": "172.10.3.80",
           "host_mask": "255.255.240.0",
           "host_gateway": "172.10.2.2",
           "primary_dns": "172.10.2.2",
           "secondary_dns": "",
           "domain_name": "local",
           "host_timezone": "America/Argentina/Buenos_Aires",
           "host_continent": "America",
           "host_city": "Argentina",
           "host_admin": "intrado_admin",
           "host_admin_password": "Int_ado1*",
           "host_security_password": "Int_ado1*",
           "host_app_user_password": "Int_ado1*",
           "certificate_organization": "Intrado-AR",
           "certificate_unit": "UCBOP-AR",
           "certificate_location": "Santa Fe",
           "certificate_state": "Santa Fe",
           "certificate_country": "AR",
           "locale_id": "",
           "ccm_version": "",
           "ccm_first_node": "yes",
           "call_home_disable": "Disabled",
           "ip_security_first_node": "yes",
           "auto_register_primary": "0",
           "app_user_username": "intrado_appuser",
           "ntp_server_1": "173.224.149.136",
           "ntp_server_2": "173.224.157.252",
           "ntp_server_3": "199.38.38.3"
          }
         },
         {
          "datacenter_name": "Denver",
          "vm_state": "poweredoff",
          "vm_name": "INTCCM1S01DEN",
          "vm_template_name": "CUCM 11.5 SU6 7500usr Skip Template",
          "full_folder_path": "/HCS Customers/"+customer_id+" - "+customer_name,
          "datastore": "datastore3",
          "host": "172.10.3.29",
          "vm_final_state": "poweredoff",
          "vm_mac": "00:50:56:97:e4:a3",
          "vm_network_name": "VM Network",
          "answer_file_config": {
           "product_type": "cucm",
           "node_type": "primary",
           "primary_host_name": "INTCCM1P01DEN",
           "primary_host_ip": "172.10.3.80",
           "host_name": "INTCCM1S01DEN",
           "host_ip": "172.10.3.84",
           "host_mask": "255.255.240.0",
           "host_gateway": "172.10.2.2",
           "primary_dns": "172.10.2.2",
           "secondary_dns": "",
           "domain_name": "local",
           "host_timezone": "America/Argentina/Buenos_Aires",
           "host_continent": "America",
           "host_city": "Argentina",
           "host_admin": "intrado_admin",
           "host_admin_password": "Int_ado1*",
           "host_security_password": "Int_ado1*",
           "host_app_user_password": "Int_ado1*",
           "certificate_organization": "Intrado-AR",
           "certificate_unit": "UCBOP-AR",
           "certificate_location": "Santa Fe",
           "certificate_state": "Santa Fe",
           "certificate_country": "AR",
           "locale_id": "",
           "ccm_version": "",
           "ccm_first_node": "no",
           "call_home_disable": "Disabled",
           "ip_security_first_node": "no",
           "app_user_username": "intrado_appuser"
          }
         },
         {
          "datacenter_name": "Denver",
          "vm_state": "poweredoff",
          "vm_name": "INTCUC1S01DEN",
          "vm_template_name": "CUCx 11.5 SU6 5000usr Skip Template",
          "full_folder_path": "/HCS Customers/"+customer_id+" - "+customer_name,
          "datastore": "datastore5",
          "host": "172.10.3.29",
          "vm_final_state": "poweredoff",
          "vm_mac": "00:50:56:97:e4:a4",
          "vm_network_name": "VM Network",
          "answer_file_config": {
           "product_type": "cucx",
           "node_type": "secondary",
           "primary_host_name": "INTCUC1P01SWN",
           "primary_host_ip": "172.10.3.83",
           "host_name": "INTCUC1S01DEN",
           "host_ip": "172.10.3.85",
           "host_mask": "255.255.240.0",
           "host_gateway": "172.10.2.2",
           "primary_dns": "172.10.2.2",
           "secondary_dns": "",
           "domain_name": "local",
           "host_timezone": "America/Argentina/Buenos_Aires",
           "host_continent": "America",
           "host_city": "Argentina",
           "host_admin": "intrado_admin",
           "host_admin_password": "Int_ado1*",
           "host_security_password": "Int_ado1*",
           "host_app_user_password": "Int_ado1*",
           "certificate_organization": "Intrado-AR",
           "certificate_unit": "UCBOP-AR",
           "certificate_location": "Santa Fe",
           "certificate_state": "Santa Fe",
           "certificate_country": "AR",
           "locale_id": "",
           "ccm_version": "",
           "ccm_first_node": "no",
           "call_home_disable": "Disabled",
           "ip_security_first_node": "no",
           "app_user_username": "intrado_appuser"
          }
         },
         {
          "datacenter_name": "Denver",
          "vm_state": "poweredoff",
          "vm_name": "INTIMP1S01DEN",
          "vm_template_name": "IM&P 11.5 SU6 5000usr Skip Template",
          "full_folder_path": "/HCS Customers/"+customer_id+" - "+customer_name,
          "datastore": "datastore5",
          "host": "172.10.3.29",
          "vm_final_state": "poweredoff",
          "vm_mac": "00:50:56:97:e4:a5",
          "vm_network_name": "VM Network",
          "answer_file_config": {
           "product_type": "im&p",
           "node_type": "secondary",
           "imp_domain_name": "somedomain",
           "primary_host_name": "INTCCM1P01DEN",
           "primary_host_ip": "172.10.3.80",
           "host_name": "INTIMP1S01DEN",
           "host_ip": "172.10.3.86",
           "host_mask": "255.255.240.0",
           "host_gateway": "172.10.2.2",
           "primary_dns": "172.10.2.2",
           "secondary_dns": "",
           "domain_name": "local",
           "host_timezone": "America/Argentina/Buenos_Aires",
           "host_continent": "America",
           "host_city": "Argentina",
           "host_admin": "intrado_admin",
           "host_admin_password": "Int_ado1*",
           "host_security_password": "Int_ado1*",
           "host_app_user_password": "Int_ado1*",
           "certificate_organization": "Intrado-AR",
           "certificate_unit": "UCBOP-AR",
           "certificate_location": "Santa Fe",
           "certificate_state": "Santa Fe",
           "certificate_country": "AR",
           "locale_id": "",
           "ccm_version": "",
           "ccm_first_node": "no",
           "ip_security_first_node": "no",
           "app_user_username": "intrado_appuser"
          }
         },
         {
          "datacenter_name": "Denver",
          "vm_state": "poweredoff",
          "vm_name": "INTEWC1P01DEN",
          "vm_template_name": "Expressway C&E",
          "full_folder_path": "/HCS Customers/"+customer_id+" - "+customer_name,
          "datastore": "datastore5",
          "host": "172.10.3.29",
          "vm_final_state": "poweredoff",
          "vm_mac": "00:50:56:97:e4:a7",
          "vm_network_name": "VM Network",
          "answer_file_config": {
           "product_type": "cucm",
           "node_type": "secondary",
           "host_name": "INTEWC1P01DEN",
           "host_ip": "172.10.3.88",
           "host_mask": "255.255.240.0",
           "host_gateway": "172.10.2.2",
           "primary_dns": "172.10.2.2",
           "secondary_dns": "",
           "domain_name": "local",
           "host_timezone": "America/Argentina/Buenos_Aires",
           "host_continent": "America",
           "host_city": "Argentina",
           "host_admin": "intrado_admin",
           "host_admin_password": "Int_ado1*",
           "host_security_password": "Int_ado1*",
           "host_app_user_password": "Int_ado1*",
           "certificate_organization": "Intrado-AR",
           "certificate_unit": "UCBOP-AR",
           "certificate_location": "Santa Fe",
           "certificate_state": "Santa Fe",
           "certificate_country": "AR",
           "locale_id": "",
           "ccm_version": "",
           "ccm_first_node": "yes",
           "call_home_disable": "Disabled",
           "ip_security_first_node": "yes",
           "auto_register_primary": "0",
           "app_user_username": "intrado_appuser",
           "ntp_server_1": "173.224.149.136",
           "ntp_server_2": "173.224.157.252",
           "ntp_server_3": "199.38.38.3"
          }
         }
        ]
      }
    }

    console.log(body_post);
    console.log(httpOptions);

    return this.http.post(this.url+job_id+'/launch/',body_post,httpOptions);
    
  }

}

